In [11]:
import numpy as np

data = np.array([[[0,1],[2,3],[4,5]],
                 [[6,7],[8,9],[10,11]],
                 [[12,13],[14,15],[16,17]],
                 [[18,19],[20,21],[22,23]],])

print(data.shape)

output = np.mean(data, axis=1)
print(output)
print(output.shape)

(4, 3, 2)
[[ 2.  3.]
 [ 8.  9.]
 [14. 15.]
 [20. 21.]]
(4, 2)


In [10]:
import numpy as np

data = np.array([[1,2,3],
                 [4,5,6],])

print(data.shape)

output = np.mean(data, axis=1)
print(output)
print(output.shape)

(2, 3)
[2. 5.]
(2,)


In [4]:
import numpy as np
points = np.array([[0,1],[2,3],[4,5],[5,2]])
indices = np.array([[0,1],[0,2],[0,3]])

edge = points[indices]
print(edge.shape)
print(edge)

(3, 2, 2)
[[[0 1]
  [2 3]]

 [[0 1]
  [4 5]]

 [[0 1]
  [5 2]]]


In [8]:
import numpy as np

points = np.array([[0,1],
                   [2,3],
                   [4,5],
                   [5,2]])

print(points.max(0))


[5 5]


$\lambda $
$$
f(x) = \int_{-\infty}^{\infty} e^{-x^2} dx
$$

In [13]:
import torch

w = torch.tensor([5], dtype=float, requires_grad=True)
b = torch.tensor([2], dtype=float, requires_grad=True)

y = w * 3 + b
y.backward()
b.requires_grad_(False)
y = w*4+b
y.backward()
b.requires_grad_(True)
y = w*4+b
y.backward()
print(w.grad)
print(b.grad)

tensor([11.], dtype=torch.float64)
tensor([2.], dtype=torch.float64)


In [7]:
import torch

fake_data = torch.randn((100,3))
target = torch.ones_like(fake_data)
print(torch.nn.functional.mse_loss(fake_data, target))
print((fake_data-target).pow(2).mean())

fake_data = torch.nn.functional.sigmoid(fake_data)
print(torch.nn.functional.binary_cross_entropy(fake_data, target))


tensor(2.0027)
tensor(2.0027)
tensor(0.8041)


In [72]:
import torch
fake_data = torch.randn((100,3))
target_real_vertex = torch.FloatTensor(fake_data.size()).uniform_(0.9, 1.0)
print(target_real_vertex)

tensor([[0.9046, 0.9336, 0.9667],
        [0.9346, 0.9017, 0.9376],
        [0.9602, 0.9335, 0.9366],
        [0.9001, 0.9887, 0.9035],
        [0.9528, 0.9021, 0.9912],
        [0.9709, 0.9314, 0.9215],
        [0.9592, 0.9524, 0.9820],
        [0.9180, 0.9522, 0.9752],
        [0.9231, 0.9658, 0.9682],
        [0.9041, 0.9598, 0.9419],
        [0.9747, 0.9842, 0.9472],
        [0.9171, 0.9221, 0.9661],
        [0.9960, 0.9687, 0.9582],
        [0.9197, 0.9048, 0.9688],
        [0.9629, 0.9048, 0.9719],
        [0.9784, 0.9963, 0.9520],
        [0.9272, 0.9165, 0.9242],
        [0.9142, 0.9896, 0.9786],
        [0.9827, 0.9003, 0.9465],
        [0.9036, 0.9482, 0.9674],
        [0.9737, 0.9564, 0.9417],
        [0.9090, 0.9791, 0.9246],
        [0.9651, 0.9698, 0.9457],
        [0.9565, 0.9851, 0.9844],
        [0.9886, 0.9244, 0.9842],
        [0.9207, 0.9614, 0.9810],
        [0.9709, 0.9786, 0.9214],
        [0.9166, 0.9136, 0.9891],
        [0.9547, 0.9594, 0.9968],
        [0.959