In [11]:
import numpy as np

data = np.array([[[0,1],[2,3],[4,5]],
                 [[6,7],[8,9],[10,11]],
                 [[12,13],[14,15],[16,17]],
                 [[18,19],[20,21],[22,23]],])

print(data.shape)

output = np.mean(data, axis=1)
print(output)
print(output.shape)

(4, 3, 2)
[[ 2.  3.]
 [ 8.  9.]
 [14. 15.]
 [20. 21.]]
(4, 2)


In [10]:
import numpy as np

data = np.array([[1,2,3],
                 [4,5,6],])

print(data.shape)

output = np.mean(data, axis=1)
print(output)
print(output.shape)

(2, 3)
[2. 5.]
(2,)


In [4]:
import numpy as np
points = np.array([[0,1],[2,3],[4,5],[5,2]])
indices = np.array([[0,1],[0,2],[0,3]])

edge = points[indices]
print(edge.shape)
print(edge)

(3, 2, 2)
[[[0 1]
  [2 3]]

 [[0 1]
  [4 5]]

 [[0 1]
  [5 2]]]


In [8]:
import numpy as np

points = np.array([[0,1],
                   [2,3],
                   [4,5],
                   [5,2]])

print(points.max(0))


[5 5]


$\lambda $
$$
f(x) = \int_{-\infty}^{\infty} e^{-x^2} dx
$$

In [13]:
import torch

w = torch.tensor([5], dtype=float, requires_grad=True)
b = torch.tensor([2], dtype=float, requires_grad=True)

y = w * 3 + b
y.backward()
b.requires_grad_(False)
y = w*4+b
y.backward()
b.requires_grad_(True)
y = w*4+b
y.backward()
print(w.grad)
print(b.grad)

tensor([11.], dtype=torch.float64)
tensor([2.], dtype=torch.float64)
